### ISSUE TITLE
全文页

### ISSUE THREAD

**Issue by yilu1015** [Leon406/wenshukt#3]
照您的思路获得`rowkey`后，用同样方法换command为`docInfoSearch`请求全文。虽然成功获得`secretKey`，但解码后没有全文。`content`显示只有`{"DocInfoVo":{}}`。请问这是怎么回事？

**Comment by Leon406** [comment]
项目手为机端, PC端请自行研究
详情里, 项目里有测试 docId

刚测试项目了,可以正常获取到信息
