### ISSUE TITLE
你好，存量数据是否可出售？

### ISSUE THREAD

**Issue by CyrusLiu158** [Leon406/wenshukt#4]
你好，可联系qq：859343455详聊

**Comment by coolbobo** [comment]
用于学习，不做商业用途



coolbobo0123@163.com
 
发件人： genghis liu
发送时间： 2020-07-30 13:33
收件人： Leon406/wenshukt
抄送： Subscribed
主题： [Leon406/wenshukt] 你好，存量数据是否可出售？ (#4)
你好，可联系qq：859343455详聊
